apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-selenium-hub
  labels:
    app: {{ .Release.Name }}-selenium-hub
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 4444
    targetPort: 4444
  - name: publish
    port: 4442
    targetPort: 4442
  - name: subscribe
    port: 4443
    targetPort: 4443
  selector:
    app: {{ .Release.Name }}-selenium-hub
