apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-selenium-node-chrome
  labels:
    app: {{ .Release.Name }}-selenium-node-chrome
spec:
  replicas: {{ .Values.chromeNode.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-selenium-node-chrome
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-selenium-node-chrome
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: selenium-node-chrome
        image: "{{ .Values.chromeNode.image.repository }}:{{ .Values.chromeNode.image.tag }}"
        ports:
          - containerPort: 5555
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: SE_EVENT_BUS_HOST
            value: "{{ .Release.Name }}-selenium-hub"
          - name: SE_EVENT_BUS_SUBSCRIBE_PORT
            value: "4443"
          - name: SE_EVENT_BUS_PUBLISH_PORT
            value: "4442"
          - name: SE_NODE_MAX_SESSIONS
            value: "4"
          - name: SE_NODE_OVERRIDE_MAX_SESSIONS
            value: "true"
          - name: START_XVFB
            value: "false"
          - name: SE_HEADLESS
            value: "true"
        {{- with .Values.chromeNode.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
