name: CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: |
          gryoussef/selenuim-tests:${{ github.sha }}
          gryoussef/selenuim-tests:latest

  package-helm:
    needs:  build-and-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.1
    - name: Package Helm chart
      run: |
        helm package ./chart
    - name: Upload Helm chart
      uses: actions/upload-artifact@v4
      with:
        name: helm-chart-${{ github.sha }}
        path: ./*.tgz